### ISSUE TITLE
Find way to make obvious what all extension methods exist in the docs

### ISSUE THREAD

**Issue by epage** [assert-rs/assert_fs#21]
Right now you have to hunt through all of the traits and it makes it hard to see the big picture.

**Comment by killercup** [comment]
All hail @QuietMisdreavus, almighty solver of docs problems:
https://twitter.com/QuietMisdreavus/status/1023416134903783429

**Comment by QuietMisdreavus** [comment]
Thank @guillaumegomez instead, he's the one who put that PR together: https://github.com/rust-lang/rust/pull/52585

**Comment by killercup** [comment]
Fixed.

> Rejoice! Our rustdoc herald @QuietMisdreavus sings the cheerful lore of @GuillaumeGomez grand accomplishments:
> https://twitter.com/QuietMisdreavus/status/1023416134903783429

**Comment by GuillaumeGomez** [comment]
You're all forgiven. :stuck_out_tongue:

**Comment by epage** [comment]
Got a couple ideas
- Add `#[doc(inline)]` in a couple places to ensure similar items are shown together rather than some being shown as re-exports
- Add a `unstable_doc` feature where I re-export `std::process::Command` and `std::process::Output` into a `doc` module.  This makes it so they will show up in my docs with all extension traits visible.
