### ISSUE TITLE
add methods to create subdirs

### ISSUE THREAD

**Issue by glehmann** [assert-rs/assert_fs#36]
I've extended the `ChildPath` in my project in order to do that — see https://github.com/glehmann/hld/commit/00bc932afdcf813da0adb43f815373c32b8576ad#diff-475a9530a9c1e888d097445199b74c2fR402

```rust
pub trait TestPathChild {
    fn child<P>(&self, path: P) -> assert_fs::fixture::ChildPath
    where
        P: AsRef<std::path::Path>;
    fn mkdir_all(&self) -> std::io::Result<()>;
}

impl TestPathChild for assert_fs::fixture::ChildPath {
    fn child<P>(&self, path: P) -> assert_fs::fixture::ChildPath
    where
        P: AsRef<std::path::Path>,
    {
        assert_fs::fixture::ChildPath::new(self.path().join(path))
    }
    fn mkdir_all(&self) -> std::io::Result<()> {
        std::fs::create_dir_all(self.path())
    }
}
```
used this way:

```rust
let tmp = assert_fs::TempDir::new().unwrap();
let subdir = tmp.child("hop").child("hop").child("hop");
let foo = subdir.child("foo.txt");
subdir.mkdir_all().unwrap();
foo.write_str(&lorem_ipsum).unwrap();
```

It might be good to support this feature natively :)

**Comment by epage** [comment]
Huh, surprised that this was overlooked.  Thanks for pointing this out!

**Comment by glehmann** [comment]
I think that the ability to create a sub clild path is missing in you commit:

```rust
let foo = subdir.child("foo.txt");
```

or maybe I just missed it :)

**Comment by epage** [comment]
Oh, I thought you were only asking about the `mkdir` part and missed the subdir part.

As a work around, you can do `temp.child("foo/bar.txt")`.

**Comment by glehmann** [comment]
thanks! :+1:
