### ISSUE TITLE
Symlink support?

### ISSUE THREAD

**Issue by chipsenkbeil** [assert-rs/assert_fs#66]
This is platform specific as it only is for unix, but is there any consideration on supporting symlinks for child paths where you have something like

```rust
let temp = assert_fs::TempDir::new().unwrap();

// Make a real file
let file = temp.child("file");
file.touch().unwrap();

// Make a symlink to a file (only available on unix platform)
temp.child("link").link(file).unwrap();
```

**Comment by epage** [comment]
1.0.4 is now released with this

**Comment by chipsenkbeil** [comment]
@epage been using assert_fs to test out [distant](https://github.com/chipsenkbeil/distant) and it's made it a lot easier and more natural than using tempfile. So thanks ton! Needed symlinks for some of my tests.
