### ISSUE TITLE
Implement Debug for TempDir

### ISSUE THREAD

**Issue by Aethelflaed** [assert-rs/assert_fs#78]
Hi there,

I'm new to rust so this might be a stupid question, but why isn't there an implementation of Debug for TempDir? Is there a specific reason or it simply wasn't needed yet?

If there's no counter reason, I'd be glad to propose a pull request

Otherwise, I'd be glad if you could provide some rational

Looking forward to reading you

Jaffa

**Comment by epage** [comment]
Available in 1.0.9.
