### ISSUE TITLE
into_persistent(_if) documentation confusion

### ISSUE THREAD

**Issue by ericcornelissen** [assert-rs/assert_fs#90]
The documentation for `.into_persistent` (and `.into_persistent_if`) suggest you can delete a persisted `TempDir` by calling `.close` on it.

https://github.com/assert-rs/assert_fs/blob/9c5caf22a4cbd0e4e4089741b6ef1fe3810fb1de/src/fixture/dir.rs#L120-L129

However, the implementation of `.close` explicitly doesn't do anything when the `TempDir` has been persisted.

https://github.com/assert-rs/assert_fs/blob/9c5caf22a4cbd0e4e4089741b6ef1fe3810fb1de/src/fixture/dir.rs#L191

So, either

1. the documentation example should be updated to clarify a persisted `TempDir` can't be deleted, or
2. the implementation of `.close` should be updated to remove `persisted `TempDir`.

---

##### Some background

I ran into this while trying to work around #51 by trying to persist-by-default and close/delete on success.

**Comment by epage** [comment]
I removed that copy/paste documentation bug in d5c06c614d9e97759940d0e3d3b99716802301b7

**Comment by epage** [comment]
btw you might find [`snapbox::path::PathFixture`](https://docs.rs/snapbox/latest/snapbox/path/struct.PathFixture.html) of interest.  The only thing it is missing compared to higher level stuff like `trycmd` is support for an env variable to control the behavior.

I personally have replaced all my uses of `assert_cmd` / `assert_fs` with `snapbox`.
