### ISSUE TITLE
copyright assigned to assert_cli developers

### ISSUE THREAD

**Issue by alexanderkjall** [assert-rs/assert_fs#91]
Here https://github.com/assert-rs/assert_fs/blob/master/LICENSE-MIT#L1 the copyright is assigned to the The assert_cli Developers, in 2015.

This might maybe be an error since the first commit is in 2018? Or is this package based on some work that they have done?

**Comment by epage** [comment]
I've fixed and clarified this

No copyright assignment is happening but it was meant to mean that individuals retain their copyright.  `asserrt_cli` was a somewhat related crate I copy/pasted from.

**Comment by alexanderkjall** [comment]
Thanks for the explanation :)

Then I'll add all parties to the copyright documentation in Debian.
